### ISSUE TITLE
How to get the order of the nodes in a diagram?

### ISSUE THREAD

**Issue by tamimi89** [Blazor-Diagrams/Blazor.Diagrams#147]
I am developing a simple workflow using Blazor Diagrams. I see the list of the nodes and links and its possible to get the order by reading all links and nodes and see which link is connected to what node. It will take me a long time to figure how to do that.

Is there a better way or someone figured out how to get the order of the nodes from the first one to the last connected node?

![SAVE_20211015_150443.jpg](https://user-images.githubusercontent.com/53964046/137448078-b1c67631-1ef2-406d-803a-5ed6ce543500.jpg)

**Comment by zHaytam** [comment]
Hello, this isn't available in the library directly because it's specific to a use case. But you could do it 2 ways:

1. Looping through all links and figuring out the order, which is what you're doing.
2. Have `Parent`/`Child` node properties in your custom node model. Whenever a link is created (Links.Added event), you set the `Parent` to either one of the source nodes of the link and the `Child` to the other. Then when you need your order, you just take your root node, which is the node without a parent but with a child, and you go through the children one by one.

**Comment by zHaytam** [comment]
Glad I helped!

**Comment by MoathTar** [comment]
> Hello, this isn't available in the library directly because it's specific to a use case. But you could do it 2 ways:
> 
> 1. Looping through all links and figuring out the order, which is what you're doing.
> 2. Have `Parent`/`Child` node properties in your custom node model. Whenever a link is created (Links.Added event), you set the `Parent` to either one of the source nodes of the link and the `Child` to the other. Then when you need your order, you just take your root node, which is the node without a parent but with a child, and you go through the children one by one.

I'm sorry for reopening this issue , but I've been trying to do this same exact thing to no avail.
I'd like to point out that the LinkAdded event triggers before the link is attached to a port or node. and doesn't get re-triggered whenever the attachment is done (mouse up on the end port).

about the other method of looping through all the links , i'm sure it's possible but whenever the link is connected in the opposite order (end port to start port) the source and target nodes are flipped which make calculating the end path complex. especially when you can reuse nodes in your diagram

 I'd love some help! love this library

**Comment by zHaytam** [comment]
Hello @MoathTar, check out #344
