### ISSUE TITLE
Is it possible to embed interactive components in LinkWidets?

### ISSUE THREAD

**Issue by jimitndiaye** [Blazor-Diagrams/Blazor.Diagrams#179]
Basically I'd like to achieve something similar to how you are positioning LinkLabels except replacing the Label text with a custom icon button. i notice that that link label is using MarkupString and therefore static HTML and so I'm not sure if embedding a button instead works.

**Comment by zHaytam** [comment]
Hello,

The use of MarkupString in the labels was forced because Blazor didnt handle foreign objects well at the time. With .NET 6, I believe it was fixed.

I think you can achieve what you want by creating a new component for labels and registering to be rendered instead of the default one. Then you can use whatever you want inside the foreign object, including buttons.

Please tell me if this helps!

**Comment by jimitndiaye** [comment]
Thanks. I'll try that and let you know.

**Comment by zHaytam** [comment]
I'll close this since I believe it's answered.
Please feel free to re-open if you think otherwise.
