### ISSUE TITLE
GetBounds() is null.

### ISSUE THREAD

**Issue by ChuckBerg** [Blazor-Diagrams/Blazor.Diagrams#199]
I'm trying to get the bounding box for each of my custom components so that I can dynamically adjust their positions at runtime.  Here's my latest attempt.

```
private NodeModel myCustomNode;

protected override void OnInitialized()
{
    base.OnInitialized();
    diagram.RegisterModelComponent<myCustomModel, myCustomComponent>();

    myCustomNode = new myCustomModel(new Point(0, 0), name);
    ...
}

protected override void OnAfterRender(bool firstRender)
{
    base.OnAfterRender(firstRender);
    var boundingBox = myCustomNode.GetBounds();
    ...
}
```
Everything renders as I expect, but it's not laid out properly.  Unfortunately, boundingBox is always null so I can't adjust positions the way I'd like.  Any thoughts?

**Comment by 314159265meow** [comment]
Hello, 

I think the reason `boundingBox` is `null` is because the bounds of a node are calculated asynchronously via JavaScript, so when you call `GetBounds()` directly in `OnAfterRender` these values haven't been calculated yet.  
You can test this if you add a button to your page and try to read the bounding box in the button event handler, there you will get the correct values.

Another way to get the bounds is to listen to the `OnChanged` or `OnSizeChanged` events of a node. These are called after the node was rendered and the size calculations are finished.

**Comment by zHaytam** [comment]
Hello,

Indeed, @314159265meow is right. Since dimensions and positions are calculated after the elements are rendered, they won't be available to you right away.

**Comment by ChuckBerg** [comment]
Thanks for the feedback, guys.  Unfortunately, I had to get something working so I've taken a different approach and am not using Blazor.Diagrams anymore.  I may switch back sometime later in the project.

Chuck

**Comment by ChuckBerg** [comment]
I only need the ability to create static flowcharts, so CSS for placement of nodes, and LeaderLine for the connecting lines and arrows.

**Comment by zHaytam** [comment]
Okay! Good luck on your project.
