### ISSUE TITLE
Problem with removing ports

### ISSUE THREAD

**Issue by 314159265meow** [Blazor-Diagrams/Blazor.Diagrams#220]
Hi, 

when you remove ports from a node, the other ports often get the wrong position and sometimes in our case have their `Initialized` property set to false. The results are not deterministic though, I think it a timing problem with the MutationObserver.

You can test it in your demo. 
Browser: Chrome 104
![Animation6_63](https://user-images.githubusercontent.com/13624874/184353672-7d4cadc8-54cc-4ad1-9def-3b10e0f6e4a6.gif)

**Comment by zHaytam** [comment]
Hello,

I can confirm the bug. I'm looking into it, thank you for letting me know.
It does look like the link is as if it's going from another port (right or top/right)

**Comment by zHaytam** [comment]
Got it!

The issue is due to how Blazor detects changes inside a for loop.

Let's take the default node widget:
```razor
    @foreach (var port in Node.Ports)
    {
        <PortRenderer Port="port" Class="default"></PortRenderer>
    }
```

It happens that the deletes ports are:
![image](https://user-images.githubusercontent.com/34218324/184507690-91a33743-be66-47f4-9732-897d9501e2f4.png)

Which leaves the Right port right? Yes! But because of the for loop & blazor, the Top port is still rendered instead.  
To fix it, we simply need to use the `@key` property:
```
    @foreach (var port in Node.Ports)
    {
        <PortRenderer @key="port" Port="port" Class="default"></PortRenderer>
    }
```

**Comment by zHaytam** [comment]
This also explains why it looks like in the demo that removing ports removes them anti clock wise. The thing is, it's random, so it shouldn't even look like that 😄

**Comment by 314159265meow** [comment]
Thank you quick help, it did some very weird things for us, like rendering non attached links and eventually throw a JS exception ("getBoundingClientRect" of null). 

![image](https://user-images.githubusercontent.com/13624874/184816378-6122358d-f619-4fcd-9874-777ce46496c2.png)

The @key attribute fixes it perfectly.
