### ISSUE TITLE
Is it possible to export and load again diagrams?

### ISSUE THREAD

**Issue by petarvu** [Blazor-Diagrams/Blazor.Diagrams#368]
Hi

We are playing with Blazor.Diagrams and are wondering about export and load functionality. Is it possible to export/load JSON diagrams?

**Comment by zHaytam** [comment]
Hello,

There is no out-of-the-box solution for export/import because the library is designed to be extensible and customizable.

However, since everything is object-oriented, you can export whatever information you want using System.Text.Json and import it how you want. For example, you create DTO classes, convert the diagram objects to those types, then simply serialize those.
