### ISSUE TITLE
Diagram seems to be impacted by external layout changes

### ISSUE THREAD

**Issue by BjornEngelen** [Blazor-Diagrams/Blazor.Diagrams#81]
I have a page that has a DiagramCanvas just below two form fields that are required. When the page is loaded these fields are empty, and will have a validation message below. When these fields are filled in the message dissappears, making the diagram shift upwards. 

Afterwards, when drawing links between nodes they appear higher than they should. The ports still react correctly when hovering, but the link is "off".

You can see what I mean in this unlisted video:
In the first try, I leave the required fields open. In the second try I make the validation errors dissappear.
https://youtu.be/RgQr3jhdw4M

This might be related: I have functionality that is able to save a diagram, and open it again later on. However, when I open an existing diagram I have to pan about 600px to the right, and 400px towards the bottom before it becomes visible. This might be due to the DiagramCanvas not being at 0,0 within the page. There is a form above it, and a toolbar to its right.

**Comment by zHaytam** [comment]
Hello,

Yes, this is a known problem that I'll be fixing soon, I'm just trying to find a clean way to do so.  
Here's what happens:

- The library gets the localtion/size of the canvas (container) and watches for resizes
- When you add an element above the diagram, without it changing the size of the canvas, the library doesn't pick this change up. This is because there is no Observer in javascript for this behavior, so I'm trying different approaches to solve it.

**Comment by zHaytam** [comment]
Also, how do you save/reload a diagram?

**Comment by BjornEngelen** [comment]
> Also, how do you save/reload a diagram?

I save the nodes that are in the diagram in a database table that has:
- The kind of node (business-value)
- X,Y position.

A second table holds the links that were created

**Comment by BjornEngelen** [comment]
When I save the diagram, I push all the nodes and links to the database table. At this point I see that a node which is created in the top-right corner will have a 0,0 coordinate.
When I load a diagram, I read what's in the database and use diagramManager.AddNode and .AddLink to rebuild it.

I've noticed DiagramManager.GetRelativePoint was in the mix in the reloading of a diagram. But after removing it I just have to pan the other way. Instead of having to pan to the right and bottom to put the diagram in the view, now I have to go left and up.

**Comment by zHaytam** [comment]
I believe that you need to also save the current Pan/Zoom values. This is because panning the diagram to the right would make it look like the nodes moved to the right. In reality, the Pan value is used to push the layers, but the nodes will stay where they were. This is why a node in 0,0 can look in the top/left corner, but also top/right, etc...

**Comment by BjornEngelen** [comment]
Hello @zHaytam,

I've upgraded this application to 2.0.0, but the behavior with the links remains the same.

However, I no longer need to pan the view after loading a diagram to get it in the visible area.

**Comment by zHaytam** [comment]
Hello,
Would it be possible to have a repro repo, please?

**Comment by BjornEngelen** [comment]
Hello @zHaytam,

I am building a repro repo. I can already tell you the cause:

The page loads a pre-saved diagram. I am loading the layout for the diagram by calling (async) to a rest service, which reads the layout from a database (async).

I was trying to create a minimal example, and once that I hardcoded the diagram in the OnInitialized instead of loading it via REST the problem was gone.

I'll continue with the minimal repro, because I would rather not dump the entire project on you.

**Comment by BjornEngelen** [comment]
Hello @zHaytam,

You can find the reproduction here: https://github.com/BjornEngelen/DiagramIssue
Sorry for the delay.

In the file EditScript.cs I put a comment on line 50:

//ZHAYTAM
//Comment/Uncomment the line below to see the difference

The visual glitch seems to be triggered by the presence or absence of this async call.

**Comment by zHaytam** [comment]
Hello @BjornEngelen, sorry for the late response. I found the issue (two actually):

- You are adding JS (`<script src="_content/Z.Blazor.Diagrams/script.min.js"></script>`) in `<head>`, it should be inside the `<body>` so that it has access to `document.body`.
- When adding nodes then links, the ports don't seem to update to include the `has-links` class, I suspect that it's because I only refresh links and not the ports when I first receive the ports dimensions, maybe I'll need to change it. To fix this, just batch all the addition operations, which will also help performance-wise (in the future).

Example of the batch:
```
Diagram.Batch(() =>
{
    NodeModel node1 = new NodeModel(new Blazor.Diagrams.Core.Geometry.Point(50, 50));
    node1.AddPort(PortAlignment.Bottom);
    Diagram.Nodes.Add(node1);

    NodeModel node2 = new NodeModel(new Blazor.Diagrams.Core.Geometry.Point(50, 200));
    node2.AddPort(PortAlignment.Top);
    Diagram.Nodes.Add(node2);

    Diagram.Links.Add(new LinkModel(node1.Ports.First(), node2.Ports.First()));
});
```

Please tell me if this fixes your issues :smile:

**Comment by BjornEngelen** [comment]
Hello @zHaytam,

Thanks, moving the script to body seems to fix my particular issue by itself.
I'll also implement the batching advise in the future.

Best regards,
